import "@mantine/core/styles.css";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ColorSchemeScript,
  MantineProvider,
  createTheme,
  mantineHtmlProps,
} from "@mantine/core";
import { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "T-Learning",
  description: "Generated by create next app",
};

const theme = createTheme({
  colors: {
    brand: [
      "#FFFBEB", // 0 - rất nhạt
      "#FFF3C4", // 1
      "#FFE88A", // 2
      "#FFDD4D", // 3
      "#FFD205", // 4 ⭐ primary
      "#E6BE00", // 5 - hover
      "#BFA000", // 6
      "#998000", // 7
      "#665500", // 8
      "#332B00", // 9 - rất đậm
    ],
  },
  primaryColor: "brand",
  primaryShade: 4, // dùng đúng màu #FFD205
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
