import "@mantine/core/styles.css";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ColorSchemeScript,
  MantineProvider,
  createTheme,
  mantineHtmlProps,
} from "@mantine/core";
import { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "T-Learning",
  description: "Generated by create next app",
};

const theme = createTheme({
  colors: {
    brand: [
      "#F2F9FF", // 0
      "#DCEEFF", // 1
      "#99c2ef", // 2
      "#66a3e6", // 3
      "#3385de", // 4
      "#3070CA", // 5
      "#265aa2", // 6
      "#1d4379", // 7
      "#132d51", // 8
      "#0a1628", // 9
    ],
  },
  primaryColor: "brand",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
